definitions:
  heartbeatResponse:
    properties:
      status:
        example: ok
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
info:
  contact:
    email: martinpfatrisch@gmail.com
    name: Martin Pfatrisch
    url: https://github.com/PfMartin
  license:
    name: All Rights Reserved
paths:
  /heartbeat:
    get:
      consumes:
      - application/json
      description: Check if the API is reachable with this route
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/heartbeatResponse'
      summary: Check heart beat
      tags:
      - heartbeat
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
